# Generated by Django 6.0.5 on 2026-05-24 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Flat File'), ('utility', 'Utility CSV'), ('travel', 'Travel JSON')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_ok', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('error_log', models.JSONField(default=list)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_by', models.CharField(default='system', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ingestion.client')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_id', models.CharField(blank=True, max_length=255)),
                ('source_raw', models.JSONField()),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel', 'Fuel Combustion'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel Stay'), ('ground_transport', 'Ground Transport')], max_length=30)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit', models.CharField(max_length=30)),
                ('quantity_original', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_original', models.CharField(max_length=30)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('is_estimated', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reason', models.CharField(blank=True, max_length=500)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionjob')),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['client', 'scope', 'activity_date'], name='ingestion_e_client__f29507_idx'), models.Index(fields=['client', 'review_status'], name='ingestion_e_client__48cab2_idx'), models.Index(fields=['job'], name='ingestion_e_job_id_7fc271_idx')],
            },
        ),
    ]
